name: Setup Metaobjects

on:
  workflow_dispatch:

jobs:
  metaobjects:
    runs-on: ubuntu-latest
    env:
      SHOPIFY_STORE: ${{ secrets.SHOPIFY_STORE }}
      SHOPIFY_ADMIN_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ADMIN_ACCESS_TOKEN }}
      SHOPIFY_API_VERSION: ${{ secrets.SHOPIFY_API_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Ensure metaobjects and metafields
        run: npm run shopify:defs